# Generated by Django 4.2.3 on 2023-08-03 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_builder_budget_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_built_year', models.IntegerField()),
                ('last_property_size', models.IntegerField(choices=[('A', '5000 sq.ft'), ('B', '3000 sq.ft'), ('C', '2000 sq.ft')], default='A', max_length=1)),
                ('last_location', models.CharField(max_length=100)),
                ('builder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.builder')),
            ],
        ),
    ]
