# Generated by Django 4.2.3 on 2023-08-03 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_propertydetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetails',
            name='last_property_size',
            field=models.IntegerField(choices=[('A', '5000 sq.ft'), ('B', '3000 sq.ft'), ('C', '2000 sq.ft')], default='A'),
        ),
    ]
