# Generated by Django 4.2.3 on 2023-08-04 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_propertydetails_last_property_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetails',
            name='last_property_size',
            field=models.IntegerField(choices=[('A', 5000), ('B', 3000), ('C', 2000)], default='A'),
        ),
    ]
