# Generated by Django 4.2.3 on 2023-08-04 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_propertydetails_last_property_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetails',
            name='last_property_size',
            field=models.IntegerField(choices=[(0, 5000), (1, 3000), (2, 2000)], default=0),
        ),
    ]
