# Generated by Django 4.2.3 on 2023-08-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_propertydetails_last_property_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='builder',
            name='contractors',
            field=models.ManyToManyField(to='main_app.contractor'),
        ),
    ]
