# Generated by Django 4.2.3 on 2023-08-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_contractor_builder_contractors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builder',
            name='appliances_included',
            field=models.CharField(choices=[('A', 'Yes'), ('B', 'No')], default='A', max_length=100),
        ),
    ]
